# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:        Autumm Caines 
subtitle:     is a Liminal Space
description:  Part technologist, part artist, part manager, part synthesizer she is passionate about the use of technology in education and the many differing facets of how technology impacts society and culture, she likes spending time at the place where differing disciplines intersect
keywords:     Autumm Caines
language:     "en" # default language of the blog. Language codes: http://www.w3schools.com/tags/ref_language_codes.asp

baseurl:      "" # the subpath of your site, e.g. /blog
url:          "http://jwillmer.github.io/jekyllDecent" # the base hostname & protocol for your site. Have a look at robots.txt as well!
permalink:    /blog/:categories/:title
cover:        /assets/mountain-cover.jpg

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
include: ['_pages']
exclude: [vendor]
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
